name: Create Deploy action

on:
  workflow_dispatch:
    inputs:
      branch:
        required: true
        type: string


jobs:
  create_workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/create-deploy-action
        with:
          userName: 'rrachitha'
          pacToken: ${{ secrets.PAC_TOKEN }}
          repoName: 'support-repo'
          branchName: ${{ github.event.inputs.branch }}
          AZURE_FUNCTIONAPP_NAME: ${{ github.event.inputs.branch }}
          AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
          DOTNET_VERSION: '3.1.0'


