name: Deploy DotNet project to function app with a Linux environment
'on': create
env:
  AZURE_FUNCTIONAPP_NAME: function-app-adp-v2-dev
  AZURE_FUNCTIONAPP_PACKAGE_PATH: ./ImageResizeFunction
  DOTNET_VERSION: 3.1.x
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action
        uses: action/checkout@v2
        with:
          repository: rrachitha/support-repo
          token: ${{ secrets.GITHUB_TOKEN}}
          ref: main
      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION}}
      - name: Resolve Project Dependencies using Dotnet
        shell: bash
        run: |-
          pushd ./${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          dotnet build --configuration Release --output ./output
          popd
      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
