name: Manual Approval workflow

on:
  workflow_dispatch:

jobs:
  build:
    name: approval
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo building

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: rrachitha
          minimum-approvals: 1

      - name: Deploy to production
        run: echo deploying
