## Create gh action and trigger deply on branch create
## Pull upstream changes from parent to child repo using repository dispatch
## Email notification can be looked into later for pull request
### Create branch --> 

## R&D-repo --- support-repo


name: Repository Dispatch
on:
  repository_dispatch:
    types: custom_event_type
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref }}
      - run: echo ${{ github.event.client_payload.sha }}